import Link from "next/link"
import { ArrowDownLeft, ArrowUpRight, FlaskConical, Landmark, Receipt, ShieldCheck, Wallet } from "lucide-react"
import { EmptyState, PageHeader, Panel, Pill, StatCard, StatusBadge } from "@/components/app/ui"
import { TX_LABEL } from "@/components/brand/helpers"
import { db } from "@/lib/db"
import { inr, shortDate } from "@/lib/format"
import { requireBrand } from "@/lib/session"
import { cn } from "@/lib/utils"

export const metadata = { title: "Payments & escrow · hustl." }

const OUTFLOW = ["ESCROW_FUND", "BRAND_FEE", "PROCESSING_FEE"]

export default async function BrandPaymentsPage() {
  const { brand } = await requireBrand()
  const [txs, deals] = await Promise.all([
    db.transaction.findMany({
      where: { deal: { brandId: brand.id } },
      include: { deal: { select: { id: true, title: true, creator: { select: { handle: true, user: { select: { name: true } } } } } }, milestone: { select: { title: true } } },
      orderBy: { createdAt: "desc" },
    }),
    db.deal.findMany({
      where: { brandId: brand.id, fundedAt: { not: null } },
      include: { creator: { select: { handle: true, user: { select: { name: true } } } }, milestones: { select: { status: true } } },
      orderBy: { fundedAt: "desc" },
    }),
  ])

  const ok = txs.filter((t) => t.status === "SUCCEEDED")
  const sum = (list: typeof ok, type: string) => list.filter((t) => t.type === type).reduce((s, t) => s + t.amount, 0)
  const funded = sum(ok, "ESCROW_FUND")
  const released = sum(ok, "RELEASE")
  const creatorFees = sum(ok, "CREATOR_FEE")
  const refunded = sum(ok, "REFUND")
  const held = Math.max(0, funded - released - creatorFees - refunded)
  const platformFees = sum(ok, "BRAND_FEE") + sum(ok, "PROCESSING_FEE")
  const frozen = txs.filter((t) => t.status === "FROZEN").reduce((s, t) => s + t.amount, 0)

  const balances = deals
    .map((d) => {
      const dt = ok.filter((t) => t.dealId === d.id)
      const f = sum(dt, "ESCROW_FUND")
      const out = sum(dt, "RELEASE") + sum(dt, "CREATOR_FEE")
      const r = sum(dt, "REFUND")
      return { deal: d, funded: f, released: out, refunded: r, held: Math.max(0, f - out - r) }
    })
    .filter((b) => b.funded > 0)
    .sort((a, b) => b.held - a.held)

  return (
    <div className="space-y-8">
      <PageHeader title="Payments & escrow" description="Money you fund sits in escrow and is released to creators only when you approve their work." />

      <div className="flex items-start gap-3 rounded-lg border border-dashed bg-muted/40 px-4 py-3 text-sm">
        <FlaskConical className="mt-0.5 size-4 shrink-0 text-muted-foreground" />
        <p className="text-muted-foreground">
          <span className="font-medium text-foreground">Test mode.</span> No real money moves. References are generated by the test adapter — Stripe Connect and Razorpay Route plug into the
          same payment service for live payouts.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Total funded" value={inr(funded)} icon={Landmark} hint={`${balances.length} funded deal${balances.length === 1 ? "" : "s"}`} />
        <StatCard label="Held in escrow" value={inr(held)} icon={ShieldCheck} hint={frozen ? `${inr(frozen)} frozen by a dispute` : "Awaiting your approval"} />
        <StatCard label="Released to creators" value={inr(released)} icon={ArrowUpRight} hint={creatorFees ? `Net of ${inr(creatorFees)} creator fees` : "Paid out on approval"} />
        <StatCard label="Platform fees paid" value={inr(platformFees)} icon={Receipt} hint={refunded ? `${inr(refunded)} refunded to you` : "Platform + processing"} />
      </div>

      <Panel title="Escrow by deal" description="What's still held on each funded deal" bodyClassName="p-0">
        {balances.length === 0 ? (
          <div className="p-5">
            <EmptyState icon={Wallet} title="Nothing funded yet" description="Once a contract is signed and you fund escrow, balances per deal show up here." />
          </div>
        ) : (
          <ul className="divide-y">
            {balances.map((b) => {
              const pctReleased = b.funded ? Math.round(((b.released + b.refunded) / b.funded) * 100) : 0
              return (
                <li key={b.deal.id}>
                  <Link href={`/brand/deals/${b.deal.id}`} className="grid gap-3 px-5 py-4 transition-colors hover:bg-muted/40 sm:grid-cols-[1fr_220px_auto] sm:items-center">
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium">{b.deal.title}</p>
                      <p className="truncate text-xs text-muted-foreground">
                        {b.deal.creator.user.name} · funded {shortDate(b.deal.fundedAt)}
                      </p>
                    </div>
                    <div>
                      <div className="mb-1 flex justify-between text-xs text-muted-foreground">
                        <span>{pctReleased}% released</span>
                        <span className="tabular-nums">{inr(b.funded)}</span>
                      </div>
                      <div className="h-1.5 overflow-hidden rounded-full bg-muted">
                        <div className="h-full rounded-full bg-success" style={{ width: `${pctReleased}%` }} />
                      </div>
                    </div>
                    <div className="flex items-center justify-between gap-3 sm:justify-end">
                      <StatusBadge status={b.deal.status} />
                      <div className="text-right">
                        <div className="text-sm font-semibold tabular-nums">{inr(b.held)}</div>
                        <div className="text-[11px] text-muted-foreground">held</div>
                      </div>
                    </div>
                  </Link>
                </li>
              )
            })}
          </ul>
        )}
      </Panel>

      <Panel title="Transaction ledger" description="Append-only record of every movement of funds" bodyClassName="p-0">
        {txs.length === 0 ? (
          <div className="p-5">
            <EmptyState icon={Receipt} title="No transactions yet" description="Escrow funding, fees, releases and refunds are all recorded here." />
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px] text-sm">
              <thead className="border-b bg-muted/40 text-left text-xs text-muted-foreground">
                <tr>
                  <th className="px-5 py-2.5 font-medium">Date</th>
                  <th className="px-3 py-2.5 font-medium">Type</th>
                  <th className="px-3 py-2.5 font-medium">Deal</th>
                  <th className="px-3 py-2.5 font-medium">Reference</th>
                  <th className="px-3 py-2.5 font-medium">Status</th>
                  <th className="px-5 py-2.5 text-right font-medium">Amount</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {txs.map((t) => {
                  const out = OUTFLOW.includes(t.type)
                  const refund = t.type === "REFUND"
                  return (
                    <tr key={t.id} className="hover:bg-muted/30">
                      <td className="px-5 py-3 whitespace-nowrap text-muted-foreground">{shortDate(t.createdAt)}</td>
                      <td className="px-3 py-3">
                        <span className="flex items-center gap-2 whitespace-nowrap">
                          <span className={cn("grid size-6 place-items-center rounded-full", out ? "bg-muted text-muted-foreground" : refund ? "bg-success-soft text-success" : "bg-accent text-accent-foreground")}>
                            {out || !refund ? <ArrowUpRight className="size-3" /> : <ArrowDownLeft className="size-3" />}
                          </span>
                          {TX_LABEL[t.type] ?? t.type}
                        </span>
                      </td>
                      <td className="max-w-[240px] px-3 py-3">
                        <Link href={`/brand/deals/${t.deal.id}`} className="block truncate hover:underline">
                          {t.deal.title}
                        </Link>
                        <span className="block truncate text-xs text-muted-foreground">
                          {t.deal.creator.user.name}
                          {t.milestone ? ` · ${t.milestone.title}` : ""}
                        </span>
                      </td>
                      <td className="px-3 py-3">
                        <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-[11px] text-muted-foreground">{t.reference}</code>
                      </td>
                      <td className="px-3 py-3">
                        <Pill tone={t.status === "SUCCEEDED" ? "success" : t.status === "FROZEN" ? "danger" : t.status === "FAILED" ? "danger" : "warning"}>
                          {t.status === "SUCCEEDED" ? "Succeeded" : t.status[0] + t.status.slice(1).toLowerCase()}
                        </Pill>
                      </td>
                      <td className={cn("px-5 py-3 text-right font-medium whitespace-nowrap tabular-nums", refund && "text-success")}>
                        {refund ? "+" : out ? "−" : ""}
                        {inr(t.amount)}
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}
      </Panel>
    </div>
  )
}
