import { createHash, randomUUID } from "node:crypto"
import path from "node:path"
import Fastify, { type FastifyInstance, type FastifyReply } from "fastify"
import { prisma, type MediaAsset } from "@hustl/db"
import { authenticate, errors, internalOrUser, ok, parse, publish, registerErrorHandler, TOPICS } from "@hustl/common"
import { createUploadRequest, mediaIdParams, signedFileQuery, UPLOAD_POLICIES, type MediaAssetDto } from "@hustl/contracts"
import { z } from "zod"
import { assertDealAccess, canViewAsset } from "./access"
import { loadContractForPdf, renderContractPdf, renderDealReport, renderMediaKit } from "./pdf"
import { verifyFileSignature } from "./signing"
import { getStorage, isLocal } from "./storage"
import { PayloadTooLargeError } from "./storage/local"

const dealIdParams = z.object({ dealId: z.string().uuid() })
const creatorIdParams = z.object({ creatorId: z.string().uuid() })

export function assetDto(a: MediaAsset): MediaAssetDto {
  return {
    id: a.id,
    ownerId: a.ownerId,
    kind: a.kind,
    status: a.status,
    fileName: a.fileName,
    mimeType: a.mimeType,
    sizeBytes: a.sizeBytes,
    dealId: a.dealId,
    createdAt: a.createdAt.toISOString(),
    readyAt: a.readyAt?.toISOString() ?? null,
  }
}

function storageKey(kind: string, id: string, fileName: string) {
  const ext = path.extname(fileName).toLowerCase()
  const now = new Date()
  return `${kind.toLowerCase()}/${now.getUTCFullYear()}/${String(now.getUTCMonth() + 1).padStart(2, "0")}/${id}${/^\.[a-z0-9]{1,8}$/.test(ext) ? ext : ""}`
}

const safeFileName = (name: string) => name.replace(/[^\w.\- ]+/g, "_")

function sendPdf(reply: FastifyReply, fileName: string, pdf: Buffer) {
  return reply
    .header("content-type", "application/pdf")
    .header("content-disposition", `inline; filename="${safeFileName(fileName)}"`)
    .header("cache-control", "private, no-store")
    .send(pdf)
}

async function findAsset(id: string) {
  const asset = await prisma.mediaAsset.findUnique({ where: { id } })
  if (!asset) throw errors.notFound("Media asset")
  return asset
}

export async function registerRoutes(app: FastifyInstance) {
  app.post("/media/uploads", { preHandler: authenticate }, async (req, reply) => {
    const input = parse(createUploadRequest, req.body)
    const policy = UPLOAD_POLICIES[input.kind]
    if (!policy.uploadable) throw errors.validation(`${input.kind} files are generated by hustl. and can't be uploaded`)
    if (!policy.mimeTypes.includes(input.mimeType))
      throw errors.validation(`File type ${input.mimeType} is not allowed for ${input.kind}`, { allowed: policy.mimeTypes })
    if (input.sizeBytes > policy.maxBytes) throw errors.validation(`File is too large for ${input.kind}`, { maxBytes: policy.maxBytes })
    if (policy.requiresDeal && !input.dealId) throw errors.validation(`${input.kind} uploads require a dealId`)
    if (input.dealId) await assertDealAccess(req, input.dealId)

    const storage = getStorage()
    const id = randomUUID()
    const asset = await prisma.mediaAsset.create({
      data: {
        id,
        ownerId: req.user!.id,
        kind: input.kind,
        bucket: storage.bucket,
        storageKey: storageKey(input.kind, id, input.fileName),
        fileName: input.fileName,
        mimeType: input.mimeType,
        sizeBytes: input.sizeBytes,
        dealId: input.dealId ?? null,
      },
    })
    const upload = await storage.createUpload(asset)
    return reply.status(201).send(ok({ asset: assetDto(asset), upload }))
  })

  // Local driver: raw body streamed to disk, size-checked.
  await app.register(async (scope) => {
    scope.removeAllContentTypeParsers()
    scope.addContentTypeParser("*", (_req, _payload, done) => done(null))
    scope.put("/media/uploads/:id/content", { preHandler: authenticate }, async (req) => {
      const { id } = parse(mediaIdParams, req.params)
      const storage = getStorage()
      if (!isLocal(storage)) throw errors.badRequest("Uploads go directly to object storage with the presigned URL")
      const asset = await findAsset(id)
      if (asset.ownerId !== req.user!.id) throw errors.forbidden()
      if (asset.status !== "PENDING_UPLOAD") throw errors.conflict(`Asset is ${asset.status}`)
      const contentType = String(req.headers["content-type"] ?? "").split(";")[0].trim().toLowerCase()
      if (contentType !== asset.mimeType) throw errors.validation(`Content-Type must be ${asset.mimeType}`)
      const declared = asset.sizeBytes ?? 0
      const length = Number(req.headers["content-length"])
      if (Number.isFinite(length) && length > declared) {
        req.raw.resume()
        throw errors.validation(`Upload exceeds the declared size of ${declared} bytes`)
      }
      try {
        const bytes = await storage.write(asset.storageKey, req.raw, declared)
        return ok({ id: asset.id, receivedBytes: bytes })
      } catch (err) {
        if (err instanceof PayloadTooLargeError) throw errors.validation(err.message)
        throw err
      }
    })
  })

  app.post("/media/uploads/:id/complete", { preHandler: authenticate }, async (req) => {
    const { id } = parse(mediaIdParams, req.params)
    const asset = await findAsset(id)
    if (asset.ownerId !== req.user!.id) throw errors.forbidden()
    if (asset.status === "READY") return ok(assetDto(asset))
    if (asset.status === "FAILED") throw errors.conflict("Upload failed; create a new upload")
    const storage = getStorage()
    const object = await storage.stat(asset.storageKey)
    if (!object) throw errors.conflict("The file has not been uploaded yet")
    const policy = UPLOAD_POLICIES[asset.kind]
    if (object.size > policy.maxBytes) {
      await storage.remove(asset.storageKey)
      await prisma.mediaAsset.update({ where: { id }, data: { status: "FAILED" } })
      throw errors.validation(`File is too large for ${asset.kind}`, { maxBytes: policy.maxBytes })
    }
    if (asset.sizeBytes !== null && object.size !== asset.sizeBytes)
      throw errors.conflict("Uploaded size does not match the declared size", { declared: asset.sizeBytes, received: object.size })
    const ready = await prisma.$transaction(async (tx) => {
      const updated = await tx.mediaAsset.update({ where: { id }, data: { status: "READY", readyAt: new Date(), sizeBytes: object.size } })
      await publish(tx, TOPICS.MEDIA_READY, updated.id, { assetId: updated.id, ownerId: updated.ownerId, kind: updated.kind, dealId: updated.dealId, mimeType: updated.mimeType })
      return updated
    })
    return ok(assetDto(ready))
  })

  // Signed local download (no session: the signature is the credential).
  app.get("/media/files/:id", async (req, reply) => {
    const { id } = parse(mediaIdParams, req.params)
    const { exp, sig } = parse(signedFileQuery, req.query)
    const check = verifyFileSignature(id, exp, sig)
    if (check === "invalid") throw errors.forbidden("Invalid download signature")
    if (check === "expired") throw errors.forbidden("Download link expired")
    const storage = getStorage()
    if (!isLocal(storage)) throw errors.notFound("File")
    const asset = await findAsset(id)
    if (asset.status !== "READY" || !(await storage.stat(asset.storageKey))) throw errors.notFound("File")
    const inline = /^(image|video)\//.test(asset.mimeType) || asset.mimeType === "application/pdf"
    return reply
      .header("content-type", asset.mimeType)
      .header("content-disposition", `${inline ? "inline" : "attachment"}; filename*=UTF-8''${encodeURIComponent(asset.fileName)}`)
      .header("x-content-type-options", "nosniff")
      .header("cache-control", `private, max-age=${Math.max(0, exp - Math.floor(Date.now() / 1000))}`)
      .send(storage.read(asset.storageKey))
  })

  app.get("/media/:id", { preHandler: internalOrUser }, async (req) => {
    const { id } = parse(mediaIdParams, req.params)
    const asset = await findAsset(id)
    if (!(await canViewAsset(req, asset))) throw errors.forbidden()
    if (asset.status !== "READY") throw errors.conflict(`Asset is ${asset.status}`)
    return ok({ asset: assetDto(asset), download: await getStorage().downloadUrl(asset) })
  })

  app.delete("/media/:id", { preHandler: authenticate }, async (req) => {
    const { id } = parse(mediaIdParams, req.params)
    const asset = await findAsset(id)
    if (asset.ownerId !== req.user!.id && req.user!.role !== "ADMIN") throw errors.forbidden()
    const [deliverables, contracts, disputes, verifications, messages] = await Promise.all([
      prisma.deliverable.count({ where: { mediaAssetId: id } }),
      prisma.contract.count({ where: { pdfMediaId: id } }),
      prisma.dispute.count({ where: { evidenceIds: { has: id } } }),
      prisma.verificationRequest.count({ where: { documentIds: { has: id } } }),
      prisma.message.count({ where: { attachmentIds: { has: id } } }),
    ])
    if (deliverables + contracts + disputes + verifications + messages > 0)
      throw errors.conflict("This file is referenced by a deal, dispute, verification or message and can't be deleted", {
        deliverables,
        contracts,
        disputes,
        verifications,
        messages,
      })
    await getStorage().remove(asset.storageKey)
    await prisma.mediaAsset.delete({ where: { id } })
    return ok({ deleted: true })
  })

  // ─── PDFs ──────────────────────────────────────────────────────────────────

  /**
   * Renders and stores the signed contract as a CONTRACT_PDF asset. Idempotent per
   * contract version + terms hash. Deal-service owns `contracts.pdf_media_id` and
   * records the returned asset id itself.
   */
  app.post("/media/contracts/:dealId/pdf", { preHandler: internalOrUser }, async (req, reply) => {
    const { dealId } = parse(dealIdParams, req.params)
    await assertDealAccess(req, dealId)
    const data = await loadContractForPdf(dealId)
    const storage = getStorage()
    const key = `contract_pdf/${dealId}/v${data.contract.version}-${data.contract.bodyHash.slice(0, 32)}.pdf`
    const existing = await prisma.mediaAsset.findUnique({ where: { storageKey: key } })
    if (existing?.status === "READY" && (await storage.stat(key)))
      return ok({ asset: assetDto(existing), download: await storage.downloadUrl(existing) })

    const pdf = await renderContractPdf(data)
    await storage.put(key, pdf, "application/pdf")
    const fileName = `contract-${dealId.slice(0, 8)}-v${data.contract.version}.pdf`
    const asset = await prisma.$transaction(async (tx) => {
      const fields = {
        status: "READY" as const,
        sizeBytes: pdf.length,
        checksum: createHash("sha256").update(pdf).digest("hex"),
        readyAt: new Date(),
        bucket: storage.bucket,
      }
      const row = existing
        ? await tx.mediaAsset.update({ where: { id: existing.id }, data: fields })
        : await tx.mediaAsset.create({
            data: { ownerId: data.deal.brand.userId, kind: "CONTRACT_PDF", storageKey: key, fileName, mimeType: "application/pdf", dealId, ...fields },
          })
      await publish(tx, TOPICS.MEDIA_READY, row.id, { assetId: row.id, ownerId: row.ownerId, kind: row.kind, dealId, mimeType: row.mimeType })
      return row
    })
    return reply.status(201).send(ok({ asset: assetDto(asset), download: await storage.downloadUrl(asset) }))
  })

  app.get("/media/contracts/:dealId/pdf", { preHandler: internalOrUser }, async (req, reply) => {
    const { dealId } = parse(dealIdParams, req.params)
    await assertDealAccess(req, dealId)
    const data = await loadContractForPdf(dealId)
    return sendPdf(reply, `contract-${dealId.slice(0, 8)}.pdf`, await renderContractPdf(data))
  })

  app.get("/media/media-kit/:creatorId", { preHandler: internalOrUser }, async (req, reply) => {
    const { creatorId } = parse(creatorIdParams, req.params)
    const pdf = await renderMediaKit(creatorId)
    return sendPdf(reply, `media-kit-${creatorId.slice(0, 8)}.pdf`, pdf)
  })

  app.get("/media/reports/deals/:dealId", { preHandler: internalOrUser }, async (req, reply) => {
    const { dealId } = parse(dealIdParams, req.params)
    await assertDealAccess(req, dealId)
    return sendPdf(reply, `deal-report-${dealId.slice(0, 8)}.pdf`, await renderDealReport(dealId))
  })
}

/** App without listening — used by tests with `inject()`. */
export async function buildApp() {
  const app = Fastify({ logger: false, bodyLimit: 1024 * 1024 })
  registerErrorHandler(app)
  await registerRoutes(app)
  await app.ready()
  return app
}

